/**
 * Created by LinChuQiang.
 */
export const ADD_TO_CART = 'ADD_TO_CART'
export const RECEIVE_PRODUCT_DATA = 'RECEIVE_PRODUCT_DATA'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'